# Generated by Django 3.2.6 on 2022-05-12 04:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.PositiveIntegerField(choices=[(0, 'Deleted'), (1, 'Added'), (2, 'Modified')])),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_to', models.DateTimeField(default=datetime.datetime(9999, 1, 1, 0, 0))),
                ('title', models.CharField(max_length=255)),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_by_from', to=settings.AUTH_USER_MODEL)),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_by_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'identity_lookup': ('user_from', 'user_to', 'title'),
            },
        ),
    ]
